2019-09-10 16:43:21,308.308 ERROR:LoggingHelper.py[line:43]: error
